name: Deploy to GCP VM
on:
  push:
    branches:
      - main  # Deploy when code is pushed to main branch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key

      - name: Deploy to GCP VM
        run: |
          ssh -i ssh_key jrdkho@34.135.55.180 "cd /var/www/html && git pull && systemctl restart apache2"